#ifndef FS_SYSTEM_H
#define FS_SYSTEM_H

#define FS_SYSTEM_MAGIC_NUMBER (uint32_t) ((0xFF << 24) | ('F' << 16) | ('S' << 8) | (0xFF))
#define FS_SYSTEM_BLOCK_SECTOR_COUNT 1
#define FS_SYSTEM_START_SECTOR 300
#define FS_SYSTEM_SECTOR_COUNT 1024
#define FS_SYSTEM_INODE_COUNT 64

#define FS_SECTOR_SIZE 512
#define FS_SYSTEM_BLOCK_SIZE FS_SYSTEM_BLOCK_SECTOR_COUNT * FS_SECTOR_SIZE

#define FS_ROOT_DIRECTORY_INODE 0

#define FS_PATH_DELIMITER '/'

#endif
